# Generated by Django 5.0.7 on 2024-07-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_book_num_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member'},
        ),
    ]
